apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-manager
  template:
    metadata:
      labels:
        app: db-manager
    spec:
      serviceAccountName: kquery
      containers:
      - name: db-manager
        image: hajelasumer422/db-manager:latest
        ports:
        - containerPort: 80
        env:
        - name: CLEANUP_INTERVAL
          value: "300"
        - name: RETENTION_PERIOD
          value: "3600"
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"       # Initial CPU request
