apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      serviceAccountName: kquery
      containers:
      - name: query
        image: hajelasumer422/query:latest
        ports:
        - containerPort: 8100
        env:
        - name: PORT
          value: "8100"
        - name: WEAVITE_HOST
          value: host.docker.internal:8080
        resources:
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "200m"       # Maximum CPU allowed (200 milliCPU)
          requests:
            memory: "128Mi"  # Initial memory request
            cpu: "100m"       # Initial CPU request
